import { storage } from "./storage";

const now = new Date().toISOString();

const SEED_RACES = [
  // ── Standard Chartered HK Marathon ──────────────────────────────────────────
  {
    name: "Standard Chartered Hong Kong Marathon",
    date: "2027-01-17",
    dateTbc: false,
    location: "Hong Kong Island",
    type: "road",
    distances: JSON.stringify(["10km", "21.1km", "42.2km"]),
    minDistanceKm: 10,
    maxDistanceKm: 42.2,
    registrationStatus: "closed",
    registrationUrl: "https://hkmarathon.com",
    sourceUrl: "https://hkmarathon.com",
    sourceName: "Hong Kong Marathon",
    description: "Hong Kong's premier road running event. Full marathon, half marathon, and 10km categories across the city's iconic harbourfront and bridges. One of Asia's largest marathons.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── HK100 Ultra ──────────────────────────────────────────────────────────────
  {
    name: "Hong Kong 100 Ultra Marathon",
    date: "2027-02-01",
    dateTbc: true,
    location: "Sai Kung – Tai Mo Shan",
    type: "trail",
    distances: JSON.stringify(["33km", "56km", "103km"]),
    minDistanceKm: 33,
    maxDistanceKm: 103,
    registrationStatus: "tbc",
    registrationUrl: "https://hk100ultra.com",
    sourceUrl: "https://hk100ultra.com",
    sourceName: "HK100 Official",
    description: "UTMB Index race. 103km from Pak Tam Chung west along Maclehose Trail, finishing with a descent from Tai Mo Shan (957m). 5,300m of elevation gain. One of Asia's most prestigious ultras.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── TransLantau by UTMB ──────────────────────────────────────────────────────
  {
    name: "TransLantau by UTMB",
    date: "2026-11-01",
    dateTbc: true,
    location: "Lantau Island",
    type: "trail",
    distances: JSON.stringify(["26km", "52km", "79km", "116km"]),
    minDistanceKm: 26,
    maxDistanceKm: 116,
    registrationStatus: "tbc",
    registrationUrl: "https://translantau.com",
    sourceUrl: "https://translantau.com",
    sourceName: "TransLantau Official",
    description: "UTMB World Series event on Lantau Island. Four distances crossing Lantau Peak (934m), Sunset Peak (869m), and South Lantau coastal trails. ITRA points available.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Oxfam Trailwalker ─────────────────────────────────────────────────────────
  {
    name: "Oxfam Trailwalker Hong Kong",
    date: "2026-11-20",
    dateTbc: true,
    location: "MacLehose Trail (Pak Tam Chung to Tuen Mun)",
    type: "trail",
    distances: JSON.stringify(["100km"]),
    minDistanceKm: 100,
    maxDistanceKm: 100,
    registrationStatus: "tbc",
    registrationUrl: "https://oxfam.org.hk/trailwalker",
    sourceUrl: "https://oxfam.org.hk/trailwalker",
    sourceName: "Oxfam HK",
    description: "The iconic 100km team charity challenge along MacLehose Trail from Pak Tam Chung to Tuen Mun. Teams of 4 complete together within 48 hours. One of Hong Kong's most beloved fundraising events.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Kerry HK Streetathon ──────────────────────────────────────────────────────
  {
    name: "Kerry Hong Kong Streetathon",
    date: "2026-11-28",
    dateTbc: true,
    location: "Hong Kong",
    type: "road",
    distances: JSON.stringify(["10km", "21.1km", "42.2km"]),
    minDistanceKm: 10,
    maxDistanceKm: 42.2,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Urban road race through Hong Kong's vibrant streets in three classic distances. A favourite for the full urban running experience.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Gammon China Coast Marathon ───────────────────────────────────────────────
  {
    name: "Gammon China Coast Marathon",
    date: "2026-12-06",
    dateTbc: true,
    location: "Hong Kong",
    type: "road",
    distances: JSON.stringify(["10km", "21km", "42km"]),
    minDistanceKm: 10,
    maxDistanceKm: 42,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Classic Hong Kong road marathon held in December. One of Asia's oldest marathon events with a rich history dating back decades.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── 4 Trails Ultra Challenge ──────────────────────────────────────────────────
  {
    name: "4 Trails Ultra Challenge (4TUL)",
    date: "2026-10-03",
    dateTbc: false,
    location: "Mong Kok to Ma On Shan, Hong Kong",
    type: "trail",
    distances: JSON.stringify(["66km", "100km"]),
    minDistanceKm: 66,
    maxDistanceKm: 100,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://ultraracecalendar.com/calendar/2026/ultras/hong-kong/",
    sourceName: "Ultra Race Calendar",
    description: "Epic multi-trail ultra challenge covering Hong Kong's four major trails in one race. Starting in Mong Kok and ending at Ma On Shan. One of HK's most brutal and celebrated ultra events.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── Raleigh Challenge Wilson Trail ───────────────────────────────────────────
  {
    name: "Raleigh Challenge – Wilson Trail",
    date: "2026-10-10",
    dateTbc: true,
    location: "Wilson Trail, New Territories",
    type: "trail",
    distances: JSON.stringify(["15km", "28km", "50km", "78km", "156km"]),
    minDistanceKm: 15,
    maxDistanceKm: 156,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Multi-distance trail challenge along the iconic Wilson Trail. Options from a short 15km to the ultimate 156km full-trail experience. All levels catered for.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Salomon LT 70 Lantau ──────────────────────────────────────────────────────
  {
    name: "Salomon LT 70 Lantau Trail Race",
    date: "2026-03-28",
    dateTbc: false,
    location: "Mui Wo, Lantau Island",
    type: "trail",
    distances: JSON.stringify(["70km"]),
    minDistanceKm: 70,
    maxDistanceKm: 70,
    registrationStatus: "closed",
    registrationUrl: null,
    sourceUrl: "https://ultraracecalendar.com/calendar/2026/ultras/hong-kong/",
    sourceName: "Ultra Race Calendar",
    description: "70km Lantau trail race starting from Mui Wo. Traverses Lantau's rugged terrain including Lantau and Sunset peaks. A beautiful and challenging ultra for seasoned trail runners.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── HK50 Series Race 1 ───────────────────────────────────────────────────────
  {
    name: "HK50 Series – Race 1: HK50",
    date: "2026-10-24",
    dateTbc: true,
    location: "Sai Kung, New Territories",
    type: "trail",
    distances: JSON.stringify(["50km"]),
    minDistanceKm: 50,
    maxDistanceKm: 50,
    registrationStatus: "tbc",
    registrationUrl: "https://actionasiaevents.com",
    sourceUrl: "https://actionasiaevents.com",
    sourceName: "Action Asia Events",
    description: "Race 1 of the Action Asia HK50 Series. 50km ultra-marathon through Sai Kung's stunning UNESCO Global Geopark. Iconic coastal and mountain terrain.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── HK50 Series Race 2 ───────────────────────────────────────────────────────
  {
    name: "HK50 Series – Race 2: Lantau 50",
    date: "2026-12-12",
    dateTbc: true,
    location: "Tung Chung, Lantau Island",
    type: "trail",
    distances: JSON.stringify(["54km"]),
    minDistanceKm: 54,
    maxDistanceKm: 54,
    registrationStatus: "tbc",
    registrationUrl: "https://actionasiaevents.com",
    sourceUrl: "https://actionasiaevents.com",
    sourceName: "Action Asia Events",
    description: "Race 2 of the HK50 Series. 54km across Lantau traversing Man Tung Road Park, Lantau Peak, and Sunset Peak. One of the most scenic ultras in Hong Kong.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── HK50 Series Race 3 ───────────────────────────────────────────────────────
  {
    name: "HK50 Series – Race 3: HK50 West",
    date: "2027-02-07",
    dateTbc: true,
    location: "New Territories West",
    type: "trail",
    distances: JSON.stringify(["11km", "25km", "55km"]),
    minDistanceKm: 11,
    maxDistanceKm: 55,
    registrationStatus: "tbc",
    registrationUrl: "https://actionasiaevents.com",
    sourceUrl: "https://actionasiaevents.com",
    sourceName: "Action Asia Events",
    description: "Race 3 of the Action Asia HK50 Series exploring the western New Territories. Three distances make this accessible for trail beginners to ultra veterans.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── HK50 Series Race 4 ───────────────────────────────────────────────────────
  {
    name: "HK50 Series – Race 4: Sai Kung 50",
    date: "2027-02-27",
    dateTbc: true,
    location: "Sai Kung, New Territories",
    type: "trail",
    distances: JSON.stringify(["13km", "22km", "35km", "54km"]),
    minDistanceKm: 13,
    maxDistanceKm: 54,
    registrationStatus: "tbc",
    registrationUrl: "https://actionasiaevents.com",
    sourceUrl: "https://actionasiaevents.com",
    sourceName: "Action Asia Events",
    description: "Race 4 of the HK50 Series returns to Sai Kung. Four distances from a fun 13km intro to a full 54km ultra. The season finale of Asia's most popular trail series.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── AirFly Trail Race ─────────────────────────────────────────────────────────
  {
    name: "AirFly Trail Race",
    date: "2027-03-15",
    dateTbc: true,
    location: "Hong Kong",
    type: "trail",
    distances: JSON.stringify(["20km", "30km"]),
    minDistanceKm: 20,
    maxDistanceKm: 30,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Trail race with 20km and 30km options. A well-organized grassroots race on Hong Kong's scenic trail network.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Mizuno HK Running Festival ────────────────────────────────────────────────
  {
    name: "Mizuno Hong Kong Running Festival",
    date: "2026-11-08",
    dateTbc: true,
    location: "Ma On Shan, New Territories",
    type: "road",
    distances: JSON.stringify(["5km", "10km", "21.1km"]),
    minDistanceKm: 5,
    maxDistanceKm: 21.1,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://ahotu.com",
    sourceName: "Ahotu Marathons",
    description: "Annual road running festival in Ma On Shan. Family-friendly event with 5km, 10km, and half marathon. Scenic harbourfront route along Tolo Harbour.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Garmin Run Asia Series HK ─────────────────────────────────────────────────
  {
    name: "Garmin Run Asia Series – Hong Kong",
    date: "2026-10-18",
    dateTbc: true,
    location: "Ma On Shan, New Territories",
    type: "road",
    distances: JSON.stringify(["5km", "10km"]),
    minDistanceKm: 5,
    maxDistanceKm: 10,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://ahotu.com",
    sourceName: "Ahotu Marathons",
    description: "Part of the Garmin Run Asia Series, Hong Kong edition. Tech-savvy race with GPS tracking and performance data. Great for runners wanting measurable improvement.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── MacLehose Trail Race ──────────────────────────────────────────────────────
  {
    name: "MacLehose Trail Race",
    date: "2026-09-26",
    dateTbc: true,
    location: "Sai Kung to Tuen Mun",
    type: "trail",
    distances: JSON.stringify(["25km", "50km", "100km"]),
    minDistanceKm: 25,
    maxDistanceKm: 100,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "One of Hong Kong's most challenging trail races along the iconic MacLehose Trail. From Sai Kung's rugged coastline through mountain wilderness to Tuen Mun.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── Lantau 2 Peaks ───────────────────────────────────────────────────────────
  {
    name: "Lantau Two Peaks Race",
    date: "2027-01-10",
    dateTbc: true,
    location: "Lantau Island",
    type: "trail",
    distances: JSON.stringify(["20km"]),
    minDistanceKm: 20,
    maxDistanceKm: 20,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Intense 20km loop over both Lantau Peak and Sunset Peak, two of Hong Kong's highest summits. Tough ascents with stunning panoramic views.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── New Year's Day Run ────────────────────────────────────────────────────────
  {
    name: "Hong Kong New Year's Day Run",
    date: "2027-01-01",
    dateTbc: false,
    location: "Victoria Park, Hong Kong Island",
    type: "road",
    distances: JSON.stringify(["5km", "10km"]),
    minDistanceKm: 5,
    maxDistanceKm: 10,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Kick off the new year with Hong Kong's beloved New Year's Day Run in Victoria Park. A festive community event welcoming runners of all abilities.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Energizer Night Race ──────────────────────────────────────────────────────
  {
    name: "Energizer Night Race",
    date: "2026-09-12",
    dateTbc: true,
    location: "Sai Kung, New Territories",
    type: "trail",
    distances: JSON.stringify(["5km", "12km", "25km"]),
    minDistanceKm: 5,
    maxDistanceKm: 25,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Run under the stars with a headlamp in one of HK's favourite night trail races. Three distances through Sai Kung's moonlit trails. A unique and atmospheric race experience.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── Dragon's Back Race ────────────────────────────────────────────────────────
  {
    name: "Dragon's Back Race",
    date: "2026-10-31",
    dateTbc: true,
    location: "Shek O, Hong Kong Island",
    type: "trail",
    distances: JSON.stringify(["22km"]),
    minDistanceKm: 22,
    maxDistanceKm: 22,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "22km race over the iconic Dragon's Back ridge on Hong Kong Island. Voted one of the world's best urban trail runs. Spectacular views of the South China Sea.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── MSIG Hong Kong Island 50 ──────────────────────────────────────────────────
  {
    name: "MSIG Hong Kong Island 50",
    date: "2026-12-05",
    dateTbc: true,
    location: "Hong Kong Island",
    type: "trail",
    distances: JSON.stringify(["12km", "25km", "50km"]),
    minDistanceKm: 12,
    maxDistanceKm: 50,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://actionasiaevents.com",
    sourceName: "Action Asia Events",
    description: "Trail race circumnavigating Hong Kong Island along its famous hiking trails. Three distances take runners past iconic peaks, beaches, and reservoirs.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── Run For A Reason ─────────────────────────────────────────────────────────
  {
    name: "Run For A Reason",
    date: "2026-12-20",
    dateTbc: true,
    location: "Central Harbourfront, Hong Kong",
    type: "road",
    distances: JSON.stringify(["5km", "10km"]),
    minDistanceKm: 5,
    maxDistanceKm: 10,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Charity road race along the Central Harbourfront. 5km and 10km options. Festive atmosphere with prizes and entertainment. All proceeds go to local charities.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Green Power Hike ─────────────────────────────────────────────────────────
  {
    name: "Green Power Hike",
    date: "2027-03-07",
    dateTbc: true,
    location: "New Territories, Hong Kong",
    type: "trail",
    distances: JSON.stringify(["15km", "33km", "50km"]),
    minDistanceKm: 15,
    maxDistanceKm: 50,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Annual fundraising trail event through the New Territories. Individual or team formats. Promotes environmental awareness while exploring Hong Kong's natural beauty.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Vibram Hong Kong 100 ──────────────────────────────────────────────────────
  {
    name: "Vibram Hong Kong 100 (Qualifier)",
    date: "2027-01-24",
    dateTbc: true,
    location: "Sai Kung – Ma On Shan – Tai Mo Shan",
    type: "trail",
    distances: JSON.stringify(["103km"]),
    minDistanceKm: 103,
    maxDistanceKm: 103,
    registrationStatus: "tbc",
    registrationUrl: "https://hk100ultra.com",
    sourceUrl: "https://hk100ultra.com",
    sourceName: "HK100 Official",
    description: "The legendary 103km qualifier event for the HK100 series. ITRA points. Starting at Pak Tam Chung, traversing Sai Kung, Ma On Shan, and finishing at Tai Mo Shan — Hong Kong's highest peak.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Happy Valley Race ─────────────────────────────────────────────────────────
  {
    name: "Happy Valley 10K",
    date: "2026-08-29",
    dateTbc: true,
    location: "Happy Valley Racecourse, Hong Kong",
    type: "road",
    distances: JSON.stringify(["5km", "10km"]),
    minDistanceKm: 5,
    maxDistanceKm: 10,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Unique run on the iconic Happy Valley Racecourse track and surrounding streets. Flat, fast, and great for PB chasers. Evening start with festive atmosphere.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── Sai Kung Coastal Trail ────────────────────────────────────────────────────
  {
    name: "Sai Kung Coastal Trail Race",
    date: "2026-09-06",
    dateTbc: true,
    location: "Sai Kung, New Territories",
    type: "trail",
    distances: JSON.stringify(["20km", "42km"]),
    minDistanceKm: 20,
    maxDistanceKm: 42,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Spectacular coastal trail race around Sai Kung's UNESCO Global Geopark. Dramatic sea cliffs, hidden beaches, and panoramic views. A must-do for any Hong Kong trail runner.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── CLP Green Power Night Run ─────────────────────────────────────────────────
  {
    name: "CLP Green Power Night Run",
    date: "2026-11-14",
    dateTbc: true,
    location: "Science Park, Shatin",
    type: "road",
    distances: JSON.stringify(["5km", "10km"]),
    minDistanceKm: 5,
    maxDistanceKm: 10,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Fun night run around Science Park in Shatin. Illuminated course with LED decorations. Environmental awareness theme. Perfect for families and casual runners.",
    isNew: false,
    createdAt: now,
    updatedAt: now,
  },
  // ── Lamma International Half Marathon ────────────────────────────────────────
  {
    name: "Lamma International Half Marathon",
    date: "2026-11-01",
    dateTbc: true,
    location: "Lamma Island",
    type: "trail",
    distances: JSON.stringify(["10km", "21.1km"]),
    minDistanceKm: 10,
    maxDistanceKm: 21.1,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Trail/road hybrid event on the car-free Lamma Island. A unique race experience away from Hong Kong's urban bustle. Take the ferry to the start and enjoy the island's relaxed atmosphere.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
  // ── Tai Mo Shan Summit Trail Race ─────────────────────────────────────────────
  {
    name: "Tai Mo Shan Summit Trail Race",
    date: "2027-02-14",
    dateTbc: true,
    location: "Tai Mo Shan, New Territories",
    type: "trail",
    distances: JSON.stringify(["15km", "30km"]),
    minDistanceKm: 15,
    maxDistanceKm: 30,
    registrationStatus: "tbc",
    registrationUrl: null,
    sourceUrl: "https://hkraces.com",
    sourceName: "HK Races",
    description: "Summit race on Hong Kong's highest peak at 957m. Both distances include the iconic summit ascent with stunning views across the Pearl River Delta on clear days.",
    isNew: true,
    createdAt: now,
    updatedAt: now,
  },
];

export async function seedIfEmpty() {
  const existing = await storage.getAllRaces();
  if (existing.length === 0) {
    for (const race of SEED_RACES) {
      await storage.insertRace(race);
    }
    console.log(`[seed] Inserted ${SEED_RACES.length} races`);
  } else {
    console.log(`[seed] DB already has ${existing.length} races, skipping seed`);
  }
}
